### ISSUE TITLE
Unable to download latest dependency VoiceAutomationClient of version 1.0.1 

### ISSUE THREAD

**Issue by BABOO468** [g-tiwari/VoiceAutomationClient#1]
receiving the below error in POM.XML  

Missing artifact com.se2automate.voice:VoiceAutomationClient:jar:1.0.1

![image](https://user-images.githubusercontent.com/42596827/44441514-8bbab700-a5ea-11e8-944b-ab496c44919f.png)

**Comment by g-tiwari** [comment]
Now use below dependency in pom - 
```
        <dependency>
            <groupId>in.co.gauravtiwari.voice</groupId>
            <artifactId>VoiceAutomationClient</artifactId>
            <version>1.0.0</version>
        </dependency>
```
update this info in pom and try again.
Please confirm and let me know

**Comment by g-tiwari** [comment]
Resolving the issue
