### ISSUE TITLE
Queries

### ISSUE THREAD

**Issue by mangeshkhaire14** [g-tiwari/VoiceAutomationClient#3]
Hi Gaurav,

I am an automation engineer and  I need voice automation in one my project. I have query regarding how this VoiceAutoamtion Server and Client works. I cloned this repository and tried to run it. I ran only function textToSpeechTest() and  in command prompt i.r in server window I get this url 

https://api.voicerss.org/?key=******&c=WAV&hl=en-us&src=Hello

Questions
1. Every time I ran the test, I need to hit this URL to check the output. Is this the correct way or is there any other way to get output results.

2. I am not getting the below logs or how I will get the filename , voicename etc.
		
LOG.info(voice.getFilename());
			LOG.info(voice.getText());
			LOG.info(voice.getVoiceName());
			LOG.info(voice.getVoiceLanguage().toString());

Thanks,
Mangesh

**Comment by g-tiwari** [comment]
Hey,

Are you able to execute this sample Voice Demo ? https://github.com/g-tiwari/GoogleVoiceTest 

Detailed description of usage are available at https://github.com/g-tiwari/VoiceAutomationClient/blob/master/README.md

Please find answer to your queries below - 
1. Yes, If you are passing text as test data , it everytime use this service to convert in to speech.
2. Ideally, it should print this info, but make sure to use it in such a way that object is already available

Also, local voice file playback feature is soon coming up in next version, as of now this whole setup work only on MAC, I am going to push my changes very soon.

Please re-open if you did not get your question answered

**Comment by mangeshkhaire14** [comment]
yes, as of now I only executed VoiceTest.java file (textToSpeechTest function).  I have executed this on windows machine.  for #2 I will  try again.

Also I have questions like how we can validate the voice responses  for example , If I give input to my voice assistant and then he will reply. so how can I validate that he will give the correct response, I mean how we can write this scenarios or scripts.

**Comment by g-tiwari** [comment]
Hey Mangesh,

I have pushed a new version of [VoiceAutomationServer](https://github.com/g-tiwari/VoiceAutomationServer/blob/master/VoiceAutomationServer-1.0.1.jar), please download that and try to execute it. I hope it should work fine.

**Comment by mangeshkhaire14** [comment]
Hi Gaurav, 

its working now and I am getting the logs also. I am still unclear on my below question,

how we can validate the voice responses for example , If I give input to my voice assistant and then he will reply. so how can I validate that he will give the correct response, I mean how we can write this scenarios or scripts. Its basically alexa like application integrated with the web application

**Comment by g-tiwari** [comment]
Hey Mangesh,
That feature is not available as of now, I am working on that. It is not that straighforward to validate voice responses. There are lot of factors involved, e.g. language, accent, and other things which varies from response to response. I am trying to figure our a way to solve this.
Meanwhile how this tool can help. 
1) Providing you the voice input based on text 
2) If it is a web application, I am sure on GUI, there would be some response based on voice input. As of now we are validating that.

Please let me know if you have further question.

**Comment by mangeshkhaire14** [comment]
ya the response is based on voice input and also we have chatbot for text input and response, do you know any other tool for chatbot automation. I heard about Botium
